# Generated by Django 2.2.14 on 2022-03-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('img', models.ImageField(upload_to='media')),
                ('txtSmall', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(max_length=35)),
                ('price', models.IntegerField()),
                ('badli', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
